@startjson
{
   "id":"8e6e7921-ac9f-4c8d-9a66-2a7a9d37a7d8",
   "orderId":"O123",
   "rootOrderId":"O123",
   "fills":[
      {
         "id":"f6556e33-8d6f-48a3-bc10-5a60c2cb801d",
         "fillId":"F123",
         "execID":"X1"
      }
   ],
   "orders":[
      {
         "id":"27041b5a-6318-4a46-8699-8db768d23b35",
         "orderId":"O456",
         "parentOrderId":"O123",
         "rootOrderId":"O123",
         "fills":[
            {
               "id":"effdd0ad-ef9d-486d-924e-f4e5211dcdb6",
               "fillId":"F456",
               "execID":"X1"
            }
         ],
         "orders":[
            
         ]
      }
   ]
}
@endjson