openapi: 3.0.3
info:
  title: Digital Assets OMS Query API
  version: 1.0.0
  description: |
    Query (read-only) API for searching Orders with dynamic filtering, pagination, and sorting.
    
    Filtering:
      - Supports equality, substring (like), numeric/date comparisons, and inclusive ranges.
      - Date-time values must be ISO-8601 local date-times (e.g. `2025-08-29T12:34:56`).
      - Enum fields only support equality: side, ordType, state, cancelState.
      - Unknown or malformed filters are ignored.
    
    Filterable fields:
      - String: orderId, rootOrderId, parentOrderId, clOrdId, account, symbol, securityId
      - Numeric: price, orderQty, cashOrderQty
      - DateTime: sendingTime, transactTime, expireTime
      - Enum: side, ordType, state, cancelState
    
    Sorting:
      - Use the `sort` query parameter with multiple segments separated by `;`.
      - Each segment: `field[,ASC|DESC]` (direction defaults to ASC).
      - Example: `sort=price,DESC;orderQty,ASC`.
      - Defaults to `id,DESC` if not specified.
    
    Pagination:
      - `page` (0-based, default 0)
      - `size` (default 50, max 500)
    
    Responses return paged lists of orders with metadata.
paths:
  /search:
    get:
      operationId: searchOrders
      summary: Dynamic search for Orders
      description: |
        Search orders with dynamic filters, pagination, and sorting.
        
        All query parameters except 'page', 'size', and 'sort' are treated as dynamic filters.
        Filter parameters follow the naming conventions described in the API description above.
        
        Examples:
          - ?symbol=BTCUSD&side=BUY
          - ?price__between=100,200&state=LIVE
          - ?orderId__like=test&page=0&size=20&sort=transactTime,DESC
      tags:
        - Orders
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
          description: 0-based page index (default 0)
        - name: size
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 500
          description: Page size (default 50, max 500)
        - name: sort
          in: query
          required: false
          schema:
            type: string
          description: Semicolon-separated list of sort instructions. Each instruction is `field[,ASC|DESC]`.
        - name: allParams
          in: query
          required: false
          schema:
            type: object
            additionalProperties:
              type: string
          style: form
          explode: true
          description: |
            Dynamic filter parameters. All query parameters (except page, size, sort) are captured as filters.
            
            Supported filter operations:
              - field=value (equality, alias for field__eq=value)
              - field__like=text (substring match, case-insensitive)
              - field__gt=value, field__gte=value, field__lt=value, field__lte=value (comparisons)
              - field__between=a,b (inclusive range, either bound can be omitted for open range)
            
            Supported fields:
              - String: orderId, rootOrderId, parentOrderId, clOrdId, account, symbol, securityId
              - Numeric: price, orderQty, cashOrderQty
              - DateTime: sendingTime, transactTime, expireTime (ISO-8601 format)
              - Enum: side, ordType, state, cancelState (equality only)
            
            Examples:
              - orderId=20250531-test-001
              - symbol__like=BTC
              - price__between=100,200
              - side=BUY
              - transactTime__between=2025-08-01T00:00:00,2025-08-31T23:59:59
      responses:
        '200':
          description: Paged list of matching orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedOrderDto'
              examples:
                basic:
                  summary: Simple symbol filter
                  value:
                    content:
                      - orderId: "20250531-test-001"
                        rootOrderId: "20250531-test-001"
                        parentOrderId: null
                        symbol: "BTCUSD"
                        side: "BUY"
                        state: "NEW"
                        ordType: "LIMIT"
                        price: 45000.00
                        orderQty: 0.5
                        transactTime: "2025-05-31T12:34:56"
                    page:
                      size: 50
                      totalElements: 1
                      totalPages: 1
                      number: 0
        '400':
          description: Bad request (invalid parameter format)
        '500':
          description: Internal server error

components:
  schemas:
    OrderDto:
      type: object
      description: Summary Order representation used in query responses.
      properties:
        orderId:
          type: string
        rootOrderId:
          type: string
        parentOrderId:
          type: string
        symbol:
          type: string
        side:
          $ref: '#/components/schemas/Side'
        state:
          $ref: '#/components/schemas/State'
        ordType:
          $ref: '#/components/schemas/OrdType'
        price:
          type: number
          description: BigDecimal represented as number
        orderQty:
          type: number
          description: BigDecimal represented as number
        transactTime:
          type: string
          format: date-time
    PagedOrderDto:
      type: object
      description: Paged collection of OrderDto
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/OrderDto'
          description: List of orders in the current page
        page:
          $ref: '#/components/schemas/PageMetadata'
    PageMetadata:
      type: object
      properties:
        size:
          type: integer
        totalElements:
          type: integer
        totalPages:
          type: integer
        number:
          type: integer
    Side:
      type: string
      enum: [BUY, SELL, SELL_SHORT, SUBSCRIBE, REDEEM]
    OrdType:
      type: string
      enum: [MARKET, LIMIT, STOP, STOP_LIMIT, MARKET_ON_CLOSE]
    State:
      type: string
      enum: [NEW, UNACK, LIVE, FILLED, CXL, REJ, CLOSED, EXP]
    CancelState:
      type: string
      enum: [CXL, PCXL, PMOD, REJ]
