openapi: 3.0.3
info:
  title: Digital Assets OMS Query API
  version: 1.0.0
  description: |
    Query (read-only) API for searching Orders with dynamic filtering, pagination, and sorting.
    
    Filtering:
      - Supports equality, substring (like), numeric/date comparisons, and inclusive ranges.
      - Date-time values must be ISO-8601 instants (e.g. `2025-08-29T12:34:56Z`).
      - Enum fields only support equality: side, ordType, state, cancelState.
      - Unknown or malformed filters are ignored.
    
    Filterable fields:
      - String: orderId, rootOrderId, parentOrderId, clOrdId, account, symbol, securityId
      - Numeric: price, orderQty, cashOrderQty
      - DateTime (Instant): sendingTime, transactTime, expireTime
      - Enum: side, ordType, state, cancelState
    
    Sorting:
      - Use the `sort` query parameter with multiple segments separated by `;`.
      - Each segment: `field[,ASC|DESC]` (direction defaults to ASC).
      - Example: `sort=price,DESC;orderQty,ASC`.
      - Defaults to `id,DESC` if not specified.
    
    Pagination:
      - `page` (0-based, default 0)
      - `size` (default 50, max 500)
    
    Responses return paged lists of orders with metadata.
paths:
  /search:
    get:
      operationId: searchOrders
      summary: Dynamic search for Orders
      description: |
        Search orders with dynamic filters, pagination, and sorting.
        
        All query parameters except 'page', 'size', and 'sort' are treated as dynamic filters.
        Filter parameters follow the naming conventions described in the API description above.
        
        Examples:
          - ?symbol=BTCUSD&side=BUY
          - ?price__between=100,200&state=LIVE
          - ?orderId__like=test&page=0&size=20&sort=transactTime,DESC
      tags:
        - Orders
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
          description: 0-based page index (default 0)
        - name: size
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 500
          description: Page size (default 50, max 500)
        - name: sort
          in: query
          required: false
          schema:
            type: string
          description: Semicolon-separated list of sort instructions. Each instruction is `field[,ASC|DESC]`.
      responses:
        '200':
          description: Paged list of matching orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedOrderDto'
        '400':
          description: Bad request (invalid parameter format)
        '500':
          description: Internal server error

components:
  schemas:
    OrderDto:
      type: object
      description: Summary Order representation used in query responses.
      properties:
        id:
          type: integer
          format: int64
        orderId:
          type: string
        parentOrderId:
          type: string
        rootOrderId:
          type: string
        tx:
          type: string
          description: Command type (Cmd enum)
        txNr:
          type: integer
          format: int64
        sessionId:
          type: string
        clOrdId:
          type: string
        sendingTime:
          type: string
          format: date-time
          x-java-type: java.time.Instant
        account:
          type: string
        origClOrdId:
          type: string
        execInst:
          type: string
          description: ExecInst enum
        handlInst:
          type: string
          description: HandlInst enum
        securityIdSource:
          type: string
          description: SecurityIdSource enum
        leg:
          type: string
          description: Leg enum
        orderQty:
          type: number
          description: BigDecimal represented as number
        cashOrderQty:
          type: number
          description: BigDecimal represented as number
        placeQty:
          type: number
          description: How much of the order quantity is placed in the market
        cumQty:
          type: number
          description: Currently executed quantity for chain of orders
        leavesQty:
          type: number
          description: Quantity open for further execution
        allocQty:
          type: number
          description: Quantity allocated to client
        positionEffect:
          type: string
          description: PositionEffect enum
        securityDesc:
          type: string
        securityType:
          type: string
          description: SecurityType enum
        maturityMonthYear:
          type: string
        strikePrice:
          type: number
          description: BigDecimal represented as number
        priceType:
          type: string
          description: PriceType enum
        putOrCall:
          type: integer
        underlyingSecurityType:
          type: string
        ordType:
          $ref: 'schema.yml#/components/schemas/OrdType'
        price:
          type: number
          description: BigDecimal represented as number
        stopPx:
          type: number
          description: BigDecimal represented as number
        securityId:
          type: string
        side:
          $ref: 'schema.yml#/components/schemas/Side'
        symbol:
          type: string
        timeInForce:
          $ref: 'schema.yml#/components/schemas/TimeInForce'
        transactTime:
          type: string
          format: date-time
          x-java-type: java.time.Instant
        exDestination:
          type: string
        settlCurrency:
          type: string
        expireTime:
          type: string
          format: date-time
          x-java-type: java.time.Instant
        securityExchange:
          type: string
        text:
          type: string
        tifTimestamp:
          type: string
          format: date-time
          x-java-type: java.time.Instant
        state:
          $ref: 'schema.yml#/components/schemas/State'
        cancelState:
          $ref: 'schema.yml#/components/schemas/CancelState'
    PagedOrderDto:
      type: object
      description: Paged collection of OrderDto
      properties:
        content:
          type: array
          x-field-extra-annotation: "@lombok.Builder.Default"
          items:
            $ref: '#/components/schemas/OrderDto'
          description: List of orders in the current page
        page:
          $ref: '#/components/schemas/PageMetadata'
    PageMetadata:
      type: object
      properties:
        size:
          type: integer
        totalElements:
          type: integer
        totalPages:
          type: integer
        number:
          type: integer
