openapi: 3.0.3
info:
  title: OMS Common Schema Definitions
  version: 1.0.0
  description: Shared schema definitions for OMS Command and Query APIs

paths: {}

components:
  schemas:
    State:
      type: string
      description: Order state
      enum:
        - NEW
        - UNACK
        - LIVE
        - FILLED
        - CXL
        - REJ
        - CLOSED
        - EXP
    CancelState:
      type: string
      description: Cancel state
      enum:
        - CXL
        - PCXL
        - PMOD
        - REJ
    Side:
      type: string
      description: Order side
      enum:
        - BUY
        - SELL
        - SELL_SHORT
        - SUBSCRIBE
        - REDEEM
    OrdType:
      type: string
      description: Order type
      enum:
        - MARKET
        - LIMIT
        - STOP
        - STOP_LIMIT
        - MARKET_ON_CLOSE
    TimeInForce:
      type: string
      description: Time in force
      enum:
        - DAY
        - GOOD_TILL_CANCEL
        - AT_THE_OPENING
        - IMMEDIATE_OR_CANCEL
        - FILL_OR_KILL
        - GOOD_TILL_CROSSING
        - GOOD_TILL_DATE
        - AT_THE_CLOSE
    Cmd:
      type: string
      description: Command type
      enum:
        - OCRE
        - OCXL
        - OREJ
        - ECRE
        - EWHK
        - EBST
    CommandStatus:
      type: string
      description: Command status
      enum:
        - OK
        - FAILED
    ExecInst:
      type: string
      description: Execution instructions
      enum:
        - NO_CROSS
        - OK_TO_CROSS
        - MID_PEG
    HandlInst:
      type: string
      description: Handling instructions
      enum:
        - AUTO
        - BROKER_INTERVENTION_OK
        - MANUAL
    SecurityIdSource:
      type: string
      description: Source of security identifier
      enum:
        - ISIN
        - RIC
        - EXCHANGE_SYMBOL
        - BLOOMBERG_SYMBOL
    PositionEffect:
      type: string
      description: Position effect (OPEN/CLOSE)
      enum:
        - OPEN
        - CLOSE
    PriceType:
      type: string
      description: Price type
      enum:
        - PERCENTAGE
        - PER_UNIT
        - FIXED_AMOUNT
        - DISCOUNT
        - PREMIUM
        - SPREAD
        - YIELD
