openapi: 3.0.3
info:
  title: Digital Assets OMS Command API
  version: 1.0.0
  description: Command API for submitting commands to oms

paths:
  /execute:
    post:
      summary: Execute an oms command
      operationId: executeCommand
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Command'
            example:
              type: "OrderCreateCmd"
              order:
                id: "20250531-test-001"
                quantity: 100
      responses:
        '200':
          description: Command executed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResult'
        '201':
          description: Command created resource successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResult'
        '400':
          description: Invalid command

components:
  schemas:
    Command:
      type: object
      discriminator:
        propertyName: type
        mapping:
          OrderCreateCmd: '#/components/schemas/OrderCreateCmd'
          OrderAcceptCmd: '#/components/schemas/OrderAcceptCmd'
          ExecutionCreateCmd: '#/components/schemas/ExecutionCreateCmd'
      required:
        - type
      properties:
        type:
          type: string
          description: Command type discriminator
        version:
          type: string
          description: Command API version

    OrderCreateCmd:
      allOf:
        - $ref: '#/components/schemas/Command'
        - type: object
          required:
            - order
          properties:
            order:
              $ref: '#/components/schemas/Order'

    OrderAcceptCmd:
      allOf:
        - $ref: '#/components/schemas/Command'
        - type: object
          required:
            - orderId
          properties:
            orderId:
              type: string
              minLength: 1

    ExecutionCreateCmd:
      allOf:
        - $ref: '#/components/schemas/Command'
        - type: object
          required:
            - execution
          properties:
            execution:
              $ref: '#/components/schemas/Execution'

    Order:
      type: object
      required:
        - clOrdId
        - account
        - ordType
        - side
        - symbol
        - orderQty
      properties:
        orderId:
          type: string
          description: Business order identifier
        parentOrderId:
          type: string
          description: Parent order identifier for child orders
        rootOrderId:
          type: string
          description: Root order identifier in order hierarchy
        sessionId:
          type: string
          description: Trading session identifier
        clOrdId:
          type: string
          description: Client order identifier
          minLength: 1
        sendingTime:
          type: string
          format: date-time
          x-java-type: java.time.Instant
          description: Time when order was sent
        account:
          type: string
          description: Trading account
          minLength: 1
        origClOrdId:
          type: string
          description: Original client order identifier for amendments/cancels
        execInst:
          allOf:
            - $ref: 'schema.yml#/components/schemas/ExecInst'
          description: Execution instructions
        handlInst:
          allOf:
            - $ref: 'schema.yml#/components/schemas/HandlInst'
          description: Handling instructions
        securityIdSource:
          allOf:
            - $ref: 'schema.yml#/components/schemas/SecurityIdSource'
          description: Source of security identifier
        orderQty:
          type: number
          description: Order quantity
          exclusiveMinimum: 0
        cashOrderQty:
          type: number
          description: Cash order quantity
        positionEffect:
          allOf:
            - $ref: 'schema.yml#/components/schemas/PositionEffect'
          description: Position effect (OPEN/CLOSE)
        securityDesc:
          type: string
          description: Security description
        securityType:
          type: string
          description: Type of security
        maturityMonthYear:
          type: string
          description: Maturity month and year for derivatives
        strikePrice:
          type: number
          description: Strike price for options
        priceType:
          allOf:
            - $ref: 'schema.yml#/components/schemas/PriceType'
          description: Price type
        putOrCall:
          type: integer
          description: Put or Call indicator (1=Put, 2=Call)
        underlyingSecurityType:
          type: string
          description: Underlying security type
        ordType:
          allOf:
            - $ref: 'schema.yml#/components/schemas/OrdType'
          description: Order type (MARKET, LIMIT, etc.)
        price:
          type: number
          description: Order price
        stopPx:
          type: number
          description: Stop price
        securityId:
          type: string
          description: Security identifier
        side:
          allOf:
            - $ref: 'schema.yml#/components/schemas/Side'
          description: Order side
        symbol:
          type: string
          description: Trading symbol
          minLength: 1
        timeInForce:
          allOf:
            - $ref: 'schema.yml#/components/schemas/TimeInForce'
          description: Time in force
        exDestination:
          type: string
          description: Execution destination
        settlCurrency:
          type: string
          description: Settlement currency
        expireTime:
          type: string
          format: date-time
          x-java-type: java.time.Instant
          description: Order expiration time
        securityExchange:
          type: string
          description: Security exchange
        text:
          type: string
          description: Free form text

    Execution:
      type: object
      required:
        - execId
        - orderId
      properties:
        execId:
          type: string
          minLength: 1
        orderId:
          type: string
          minLength: 1

    CommandResult:
      type: object
      properties:
        id:
          type: string
          description: unique identifier for object created by the command
        status:
          $ref: 'schema.yml#/components/schemas/CommandStatus'
        message:
          type: string
          description: human-readable description of the command result