spring:
  application:
    name: transactions
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
  docker:
    compose:
      enabled: false
      file: docker-compose.yml
  jackson:
    serialization:
      write-dates-as-timestamps: false
     
springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: actuator,health,info