spring:
  application:
    name: transactions
  data:
    redis:
      cluster:
        nodes: oms-redis-cluster:6379
        max-redirects: 3
      #host: localhost
      #port: 6379
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
  docker:
    compose:
      enabled: false
      file: docker-compose.yml
  jackson:
    serialization:
      write-dates-as-timestamps: false
     
springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: actuator,health,info,metrics,prometheus

server:
  port: 8888