spring:
  rsocket:
    server:
      port: 7000
      transport: tcp
  jackson:
    serialization:
      write-dates-as-timestamps: false
server:
  port : 8080
logging:
  level:
    root: INFO
    org.example.rsocket.server: DEBUG